# Generated by Django 4.0.3 on 2022-04-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
