# Generated by Django 4.0.4 on 2022-07-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_delete_list_todo_address_todo_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
